### ISSUE TITLE
sls deploy fail

### ISSUE THREAD

**Issue by roperluo32** [serverless-components/tencent-mongodb#2]
## serverless.yaml
component: mongodb
name: mongoDBDemoMongo
org: anycodes
app: mongoDBAPP
stage: dev

inputs:
  name: Mydemo

## error msg

serverless ⚡ framework
Action: "deploy" - Stage: "dev" - App: "mongoDBAPP" - Instance: "mongoDBDemoMongo"

 Error: {"Response":{"Error":{"Code":"InvalidParameter","Message":"EnvId is invalid"},"RequestId":"eef8b789-60ad-4b97-a23a-1a36d9c0f8e8"}}
    at Express.deploy (/var/user/serverless.js:54:13)
    at process._tickCallback (internal/process/next_tick.js:68:7)

22s » mongoDBDemoMongo » {"Response":{"Error":{"Code":"InvalidParameter","Message":"EnvId is invalid"},"RequestId":"eef8b789-60ad-4b97-a23a-1a36d9c0f8e8"}}

**Comment by zchuhui** [comment]
me too....

**Comment by AprilJC** [comment]
The environment name only support lower case letters, so that the inputs.name should be 'mydemo', sorry for the inconvenience, we'll fix it right now.
